#os valores estão setado deixado aqui apenas para facilitar os testes e dev, mas isso não deve ficar aqui em um ambiente real
APP_SPOTIFY_KEY: e359cda92a394e08a39237346311471b
APP_SPOTIFY_SECRET: c3f4976f68154e0a864160733cf7cdcc
APP_OPENWEATHER_APPID: d1b7f11761729386d59886df8fb09e8c

APP_REDIS_HOST: localhost
APP_REDIS_PORT: 6379