global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  
  - job_name: 'service-user'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus' #path da aplicação
    static_configs:
      - targets: ['host.docker.internal:8080'] #Servidor da minha aplicação    

  - job_name: 'spring-boot-suggestion-track'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus' #path da aplicação
    static_configs:
      - targets: ['host.docker.internal:8081'] #Servidor da minha aplicação